[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "4.5.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:webpack"

[dev]
  framework = "hugo"
  targetPort = 3000

